[package]
name = "py2o2-testing"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
pyo3.workspace = true

[dependencies.py2o2-runtime]
path = "../py2o2-runtime"

[build-dependencies]
anyhow.workspace = true

[build-dependencies.py2o2]
path = "../py2o2"
