[package]
name = "py2o2-testing"
version = "0.1.0"
edition = "2021"

[dependencies]
py2o2-runtime.workspace = true
anyhow.workspace = true
pyo3.workspace = true

[build-dependencies]
py2o2.workspace = true
anyhow.workspace = true
