- name: add
  description: Add new features.
  color: "006400"
- name: change
  description: Change existing functionality.
  color: "fbca04"
- name: deprecate
  description: Mark as soon-to-be removed features.
  color: "a9a9a9"
- name: remove
  description: Remove features.
  color: "dda0dd"
- name: bug
  description: Fix bug.
  color: "dc143c"
- name: security
  description: In case of vulnerabilities.
  color: "800080"
