[package]
name = "pyroxide-example"
version = "0.1.0"
edition = "2021"

default-run = "pyroxide-example"

[dependencies.pyo3]
version = "0.18.3"
features = ["auto-initialize"]

[build-dependencies.pyroxide]
path = "../pyroxide"
