[package]
name = "pyreoxide-example"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = "0.18.3"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.pyreoxide]
path = "../pyreoxide"
