[package]
name = "pyroxide-testing"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
pyo3 = { version = "0.18.3", features = ["auto-initialize"] }
pyroxide = { path = "../pyroxide" }

[build-dependencies]
anyhow = "1"
pyroxide = { path = "../pyroxide" }
