[package]
name = "pyroxide-testing"
version = "0.1.0"
edition = "2021"

[dependencies.pyo3]
version = "0.18.3"
features = ["auto-initialize"]

[build-dependencies]
anyhow = "1"

[build-dependencies.pyroxide]
path = "../pyroxide"
