name: External packages

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  numpy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: |
        pip install numpy
    - uses: actions-rs/cargo@v1
      with:
        command: run
        args: -- inspect numpy