name: witgen

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - "example"
          - "type-aliases"

    steps:
    - uses: actions/checkout@v1
    - name: witgen
      run: |
        ./witgen.py python/$(echo ${{ matrix.target }} | sed "s/-/_/g").py > ${{ matrix.target }}.wit
        diff ${{ matrix.target }}.wit python/${{ matrix.target }}.wit
