name: witgen

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: witgen
      run: |
        diff python/example.wit <(./witgen.py python/example.py)
