name: witgen

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: witgen
      run: |
        ./witgen.py pyroxide/tests/example.py > example.wit
        diff example.wit pyroxide/tests/example.wit
